```{r setup}
library(tidyverse)
library(dplyr)
library(MASS)
library(AER)
library(coefplot)
```

# 普通のiv法
```{r}
gen_data <- function(N, nX, nW, nZ, beta){
  u <- rnorm(N)
  v <- rnorm(N)
  Z <- rnorm(N * nZ) %>% 
    array(dim = c(N, nZ)) %>% 
    cbind(1, .)
  gamma <- array(rnorm(nX * (nZ + 1)), dim = c(nZ + 1, nX))
  X <- Z %*% gamma + u + v
  W <- rnorm(N * nW) %>% 
    array(dim = c(N, nW)) %>% 
    cbind(1, .)
  XW <- cbind(X, W)
  y <- XW %*% array(beta, dim = c(nX + nW + 1, 1)) + u
  data <-  cbind(y, XW, Z, u, v) %>% 
    as.data.frame()
  col_names <- c("y", 
                 lapply(1:nX, FUN = function(i){paste("X", i, sep = "")}),
                 lapply(0:nW, FUN = function(i){paste("W", i, sep = "")}),
                 lapply(0:nZ, FUN = function(i){paste("Z", i, sep = "")}))
  colnames(data) <- col_names
  output <- c()
  output$data <- data
  output$y <- y
  output$X <- X
  output$W <- W
  output$Z <- Z
  output$beta <- beta
  output$gamma <- gamma
  output$u <- u
  output$v <- v
  return(output)
}
```

```{r}
data <- gen_data(1000, 2, 2, 5, 1)
resultIV <- ivreg(y ~ X1 + X2 + W1 + W2 | Z1 + Z2 + Z3 + Z4 + Z5, data = data$data)
coefplot(resultIV) + xlim(-3, 3) + geom_vline(xintercept = 1)
```


```{r}
gen_data_weak <- function(N, nX, nW, nZ1, nZ2, beta){
  u <- rnorm(N)
  v <- rnorm(N)
  nZ <- nZ1 + nZ2
  Z1 <- rnorm(N * nZ1) %>% 
    array(dim = c(N, nZ1)) %>% 
    cbind(1, .)
  Z2 <- rnorm(N * nZ2) %>% 
    array(dim = c(N, nZ2))
  Z <- cbind(Z1, Z2)
  gamma <- array(rnorm(nX * (nZ1 + 1)), dim = c(nZ1 + 1, nX))
  X <- Z1 %*% gamma + u + v
  W <- rnorm(N * nW) %>% 
    array(dim = c(N, nW)) %>% 
    cbind(1, .)
  XW <- cbind(X, W)
  y <- XW %*% array(beta, dim = c(nX + nW + 1, 1)) + u
  data <-  cbind(y, XW, Z, u, v) %>% 
    as.data.frame()
  col_names <- c("y", 
                 lapply(1:nX, FUN = function(i){paste("X", i, sep = "")}),
                 lapply(0:nW, FUN = function(i){paste("W", i, sep = "")}),
                 lapply(0:nZ, FUN = function(i){paste("Z", i, sep = "")}))
  colnames(data) <- col_names
  output <- c()
  output$data <- data
  output$y <- y
  output$X <- X
  output$W <- W
  output$Z <- Z
  output$beta <- beta
  output$gamma <- gamma
  output$u <- u
  output$v <- v
  return(output)
}
```

```{r}
data_weak <- gen_data_weak(1000, 2, 2, 10, 9, 1)
resultIVweak <- ivreg(y ~ X1 + X2 + W1 + W2 |
                        Z1 + Z2 + Z3 + Z4 + Z5 + Z6 + Z7 + Z8 + Z9 + Z10, 
                      data = data_weak$data)
coefplot(resultIVweak) + geom_vline(xintercept = 1)
```

# 同時決定のデータ
```{r}
gen_se_data <- function(N, sigma12 = 0.5){
  # y1 = alpha1 + gamma1 * y2 + X1 %*% beta1 + u1
  # y2 = alpha2 + gamma2 * y1 + X2 %*% beta2 + u2
  alpha1 <- 1
  alpha2 <- 1
  gamma1 <- 1
  gamma2 <- -1
  beta1 <- 1
  beta2 <- 1
  u <- mvrnorm(n = N, c(0, 0), Sigma = matrix(c(1, sigma12, sigma12, 1), 2, 2))
  u1 <- u[,1]
  u2 <- u[,2]
  X1 <- matrix(rnorm(N))
  X2 <- matrix(rnorm(N))
  y2 <- (gamma2 * (alpha1 + beta1 * X1 + u1) + alpha2 + beta2 * X2 + u2) / (1 - gamma1 * gamma2)
  y1 <- alpha1 + gamma1 * y2 + beta1 * X1 + u1

  data <- tibble(
    "y1" = y1[,1],
    "y2" = y2[,1],
    "x1" = X1[,1],
    "x2" = X2[,1]
  )
  return(data)
}
gen_se_data(10)
```

```{r}
data <- gen_se_data(1000)
```

```{r}
resultOLS <- lm(y1 ~ y2, data = data)
coefplot(resultOLS) + geom_vline(xintercept = 1)
```

```{r}
resultIV <- ivreg(y1 ~ y2 | x2, data = data)
coefplot(resultIV) + geom_vline(xintercept = 1)
```

```{r}
resultReduced1 <- lm(y1 ~ x1 + x2, data = data)
coefplot(resultReduced1) + geom_vline(xintercept = c(0.5, 1))
```

```{r}
resultReduced2 <- lm(y2 ~ x1 + x2, data = data)
coefplot(resultReduced2) + geom_vline(xintercept = c(-0.5, 0.5))
```

```{r}
gen_se_data <- function(N){
  # y1 = alpha1 + lambda1 * z1 + lambda2 * z2 + u1
  # y2 = alpha2 + gamma1 * z1 + gamma2 * z2 + u2
  
}
```

